# Generated by Django 5.0.1 on 2026-02-06 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
                ('crowd_preference', models.CharField(choices=[('quiet', 'Quiet & Peaceful'), ('moderate', 'Moderate'), ('lively', 'Lively & Crowded')], default='moderate', max_length=20)),
                ('activity_level', models.CharField(choices=[('relaxed', 'Relaxed & Chill'), ('balanced', 'Balanced'), ('adventurous', 'Adventurous & Active')], default='balanced', max_length=20)),
                ('distance_preference', models.CharField(choices=[('nearby', 'Nearby (0-50 km)'), ('moderate', 'Moderate (50-200 km)'), ('far', 'Far Away (200+ km)')], default='moderate', max_length=20)),
                ('budget_conscious', models.BooleanField(default=False)),
                ('nature_lover', models.BooleanField(default=True)),
                ('culture_enthusiast', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
                ('destination_name', models.CharField(max_length=255)),
                ('destination_id', models.CharField(max_length=100)),
                ('location_lat', models.FloatField()),
                ('location_lon', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('trip_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
                ('destination_name', models.CharField(max_length=255)),
                ('destination_id', models.CharField(max_length=100)),
                ('location_lat', models.FloatField()),
                ('location_lon', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('session_key', 'destination_id')},
            },
        ),
    ]
